# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Israel Brea Piñero"
weight = 1


[es]
languageName = "Español"
languagedirection = "ltr"
title = "Israel Brea Piñero"
weight = 2