# Configure main menu and social menu
#[[main]]
#identifier = "home"
#name = "Home"
#url = "/"
#[main.params]
#icon = "home"
#newtab = true

[[social]]
identifier = "github"
name = "GitHub"
url = "https://github.com/israelbrea12"

[social.params]
icon = "brand-github"


[[social]]
identifier = "linkedin"
name = "LinkedIn"
url = "https://www.linkedin.com/in/israel-brea-pi%C3%B1ero-79747b282/"

[social.params]
icon = "brand-linkedin"